export const BORROW_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  BORROWED: 'BORROWED',
  RETURNED: 'RETURNED',
};
s
const VALID_TRANSITIONS = {
  [BORROW_STATUS.PENDING]: [
    BORROW_STATUS.APPROVED,
    BORROW_STATUS.REJECTED,
    BORROW_STATUS.CANCELLED,
  ],
  [BORROW_STATUS.APPROVED]: [
    BORROW_STATUS.BORROWED,
    BORROW_STATUS.CANCELLED,
  ],
  [BORROW_STATUS.BORROWED]: [BORROW_STATUS.RETURNED],
  [BORROW_STATUS.REJECTED]: [],
  [BORROW_STATUS.CANCELLED]: [],
  [BORROW_STATUS.RETURNED]: [],
};

export function isValidStatusTransition(currentStatus, nextStatus) {
  const allowed = VALID_TRANSITIONS[currentStatus] || [];
  return allowed.includes(nextStatus);
}